### ISSUE TITLE
Error when running - ImportError: No module named requests

### ISSUE THREAD

**Issue by ShanikaEdiriweera** [bregman-arie/reqwise#6]
After installing reqwise when the `reqwise` command is given this error occurs.
```    
Traceback (most recent call last):
  File "/usr/local/bin/reqwise", line 6, in <module>
    from reqwise.cmd import main
  File "/usr/local/lib/python2.7/dist-packages/reqwise/cmd.py", line 17, in <module>
    from manager import Manager
  File "/usr/local/lib/python2.7/dist-packages/reqwise/manager.py", line 22, in <module>
    from sources.copr import Copr
  File "/usr/local/lib/python2.7/dist-packages/reqwise/sources/copr.py", line 18, in <module>
    import requests
ImportError: No module named requests
```

**Comment by bregman-arie** [comment]
Thanks! fixed :)

**Comment by ShanikaEdiriweera** [comment]
The issue is still there when I run `reqwise`
